<a href="https://colab.research.google.com/github/yihan4326/MSSP607/blob/main/WeeklyModules/Week05/PARTICIPATION_ACTIVITY_Week_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Clone GitHub repository to Colab and read csv files
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import statsmodels.formula.api as sm
import statsmodels.api as se
import seaborn as sns
import datetime as dt
from sklearn.linear_model import LinearRegression
from scipy import stats
from io import StringIO
import itertools

pd.set_eng_float_format(accuracy=3, use_eng_prefix=True)
pd.set_option('display.float_format', lambda x: '%.2f' % x)

from google.colab import userdata
import os
import subprocess

# Get GitHub token from Colab Secrets
github_token = userdata.get('Git_Hub')

# Set the GitHub repository owner and name
owner = 'yihan4326'
repository = 'MSSP607'

# Create the clone URL
clone_url = f'https://{github_token}@github.com/{owner}/{repository}.git'

# Clone the repository
subprocess.run(['git', 'clone', clone_url])

# Navigate into the cloned repository
os.chdir(repository)

# Read each FAANG csv file into a DataFrame
aapl = pd.read_csv('data/aapl.csv')
amzn = pd.read_csv('data/amzn.csv')
nflx = pd.read_csv('data/nflx.csv')
fb = pd.read_csv('data/fb.csv')
goog = pd.read_csv('data/goog.csv')
aapl.head()

         date   open   high    low  close    volume
0  2018-01-02 166.93 169.03 166.04 168.99  25555934
1  2018-01-03 169.25 171.23 168.69 168.96  29517899
2  2018-01-04 169.26 170.17 168.81 169.74  22434597
3  2018-01-05 170.14 172.04 169.76 171.68  23660018
4  2018-01-08 171.04 172.27 170.63 171.04  20567766

In [ ]:
# Read each file into a dataframe
aapl = pd.read_csv(data_folder / 'aapl.csv')
amzn = pd.read_csv(data_folder / 'amzn.csv')
nflx = pd.read_csv(data_folder / 'nflx.csv')
fb = pd.read_csv(data_folder / 'fb.csv')
goog = pd.read_csv(data_folder / 'goog.csv')

In [ ]:
# Add ticker column
aapl['ticker'] = 'AAPL'
amzn['ticker'] = 'AMZN'
nflx['ticker'] = 'NFLX'
fb['ticker'] = 'FB'
goog['ticker'] = 'GOOG'

In [ ]:
# create a single dataframe
faang = pd.concat([fb, aapl, amzn, nflx, goog])
faang.head()

         date    open    high       low   close    volume ticker
0  2018-01-02  177.68  181.58  177.5500  181.42  18151903     FB
1  2018-01-03  181.88  184.78  181.3300  184.67  16886563     FB
2  2018-01-04  184.90  186.21  184.0996  184.33  13880896     FB
3  2018-01-05  185.59  186.90  184.9300  186.85  13574535     FB
4  2018-01-08  187.20  188.90  186.3300  188.28  17994726     FB

In [ ]:
# Save faang.csv
faang.to_csv(data_folder / 'faang.csv', index=False)

In [ ]:
# Read faang.csv and change data types
faang = pd.read_csv(data_folder / 'faang.csv')
faang['date'] = pd.to_datetime(faang['date'])
faang['volume'] = faang['volume'].astype(int)
faang = faang.sort_values(['date', 'ticker'])
faang.head()

           date       open       high        low      close    volume ticker
251  2018-01-02   166.9271   169.0264   166.0442   168.9872  25555934   AAPL
502  2018-01-02  1172.0000  1190.0000  1170.5100  1189.0100   2694494   AMZN
0    2018-01-02   177.6800   181.5800   177.5500   181.4200  18151903     FB
1004 2018-01-02  1048.3400  1066.9400  1045.2300  1065.0000   1237564   GOOG
753  2018-01-02   196.1000   201.6500   195.4200   201.0700  10966889   NFLX

In [ ]:
# The 7 rows with highest volume
faang.sort_values('volume', ascending=False).head(7)
print(faang.sort_values('volume', ascending=False).head(7))

          date      open      high       low     close     volume ticker
142 2018-07-26  174.8900  180.1300  173.7500  176.2600  169803668     FB
53  2018-03-20  167.4700  170.2000  161.9500  168.1500  129851768     FB
57  2018-03-26  160.8200  161.1000  149.0200  160.0600  126116634     FB
54  2018-03-21  164.8000  173.4000  163.3000  169.3900  106598834     FB
433 2018-09-21  219.0727  219.6482  215.6097  215.9768   96246748   AAPL
496 2018-12-21  156.1901  157.4845  148.9909  150.0862   95744384   AAPL
463 2018-11-02  207.9295  211.9978  203.8414  205.8755   91328654   AAPL

In [ ]:
# Use melt()
faang_long = faang.melt(id_vars=['date', 'ticker'])
faang_long.head()

        date ticker variable      value
0 2018-01-02   AAPL     open   166.9271
1 2018-01-02   AMZN     open  1172.0000
2 2018-01-02     FB     open   177.6800
3 2018-01-02   GOOG     open  1048.3400
4 2018-01-02   NFLX     open   196.1000